package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"fmt"

	"github.com/zhenyanesterkova/nepblog/internal/gql/model"
	"github.com/zhenyanesterkova/nepblog/internal/gql/runtime"
)

// ChildComments is the resolver for the childComments field.
func (r *commentResolver) ChildComments(ctx context.Context, obj *model.Comment) (model.CommentResolvingResult, error) {
	panic(fmt.Errorf("not implemented: ChildComments - childComments"))
}

// Comment returns runtime.CommentResolver implementation.
func (r *Resolver) Comment() runtime.CommentResolver { return &commentResolver{r} }

type commentResolver struct{ *Resolver }
