package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"

	"github.com/zhenyanesterkova/nepblog/internal/gql/model"
	"github.com/zhenyanesterkova/nepblog/internal/gql/runtime"
)

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context) (*model.PostQuery, error) {
	return &model.PostQuery{}, nil
}

// PostQuery returns runtime.PostQueryResolver implementation.
func (r *Resolver) PostQuery() runtime.PostQueryResolver { return &postQueryResolver{r} }

type postQueryResolver struct{ *Resolver }
