package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"

	"github.com/zhenyanesterkova/nepblog/internal/feature/post"
	"github.com/zhenyanesterkova/nepblog/internal/gql/model"
)

// Fetch is the resolver for the fetch field.
func (r *postQueryResolver) Fetch(ctx context.Context, obj *model.PostQuery, filter *model.PostFetchFilterInput, sort model.PostFetchSortEnum, pageSize uint, pageNumber uint) (model.PostFetchResult, error) {
	posts, err := r.Repo.FetchPosts(ctx, filter.IDAnyOf)
	if err != nil {
		return NewInternalErrorProblem(), nil
	}

	return model.PostFetchList{
		Items: post.MapManyToGqlModels(posts),
	}, nil
}
